runtime: python39
env: standard

instance_class: F2
automatic_scaling:
  min_instances: 0
  max_instances: 10
  target_cpu_utilization: 0.6

handlers:
- url: /static
  static_dir: frontend/dist
  secure: always

- url: /.*
  script: auto
  secure: always

env_variables:
  FLASK_ENV: production